#!/bin/bash
clear
echo ""
echo ""
echo ""
echo ""
echo "********** Welcome to One-Touch Data Processing Framework for AWS !! **************"
echo ""
echo ""
echo "********** We will setup a Reference Architecture for Data Processing, using Infrastructure-as-Code !! **************"
echo ""
echo ""
echo ""
echo ""
echo "****** First, we will build our Data Processing component ******"
echo ""
echo ""
echo ""
echo ""
echo ""
cd ../aws-iot-edge-solution
gdk component build
echo ""
echo ""
echo ""
echo ""
echo "****** Let's publish our Data Processing component in AWS ******"
echo ""
echo ""
echo ""
echo ""
gdk component publish
echo ""
echo ""
echo ""
echo ""
echo "****** Now we will publish Nano MQTT Broker as a custom component in AWS ******"
echo ""
echo ""
echo ""
echo ""
echo ""
cd ../aws-iot-mqtt-component
gdk component publish
echo ""
echo ""
echo ""
echo ""
cd ../aws-iot-terraform-scripts
echo ""
echo ""
echo ""
echo ""
echo "******** Now, we will provision AWS resources *******"
echo ""
echo ""
echo ""
echo ""
terraform plan
echo ""
echo ""
echo ""
echo ""
terraform apply -auto-approve

echo ""
echo ""
echo ""
echo ""
echo ""
echo "********* All AWS Cloud Resources have been provisioned, including creation of a EC2 instance that will act as an Edge Device !! ***********"
echo ""
echo ""
echo ""
echo ""
echo ""

echo "********* Now, let's configure the Gateway Edge Device and install AWS Greengrass components therein ********"
echo ""
echo ""
echo ""
echo ""
echo "********* You can skip this step if you want to bring-in your own Physical Edge Device ********"
./provision-physical-edge-device.sh ec2ip.txt gatewaydevicearn.txt devicegrouparn.txt
echo ""
echo ""
echo ""
echo ""

echo "********* Congrats !! You are now all set !! Go ahead and start processing your data *********"
echo ""
echo ""
echo "********* Good Bye !! ********"
echo ""
